name: Generate Snake Animation

on:
  schedule:
    # Runs at midnight daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user: arpita-32 # Corrected input key

      - name: Output Snake Animation
        run: |
          mkdir -p dist && cp .github/snake.svg dist/snake.svg

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
